spring:
  application:
    name: tcgl-job-@datakey@-@nameSuffix@
  cloud:
    nacos:
      discovery:
        server-addr: @nacosHost@
        group: @datakey@
        enabled: true
        heart-beat-interval: 5
        heart-beat-timeout: 30

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcgl
    username: root
    password: 123456

server:
  port: 8083
