debug: true
server:
  port: 8090
dubbo:
  application:
    name: dubbo-consumer
  protocal:
#    id: dubbo
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
spring:
  devtools:
    restart:
      enabled: true  #热部署