spring:
  application:
    name: tcgl-provider-@datakey@-@nameSuffix@
  cloud:
    nacos:
      discovery:
        server-addr: @nacosHost@
        group: @datakey@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 123456
    hikari:
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 5000
#      最小空闲连接数量
      minimum-idle: 3
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 50
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 120000
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 300000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      connection-test-query: select 1
mybatis-plus:
  configuration:

    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.tcgl.provider.model
  global-config:
    db-config:
      table-underline: true
